// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/instance/v1/instance_service_api.proto

package network.cow.mooapis.instance.v1;

public interface DeleteInstanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.instance.v1.DeleteInstanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
