// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/instance/v1/types.proto

package network.cow.mooapis.instance.v1;

public interface MetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.instance.v1.Metadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The currently observed state. The underlying application
   * that is running can define this state
   * </pre>
   *
   * <code>string state = 1 [json_name = "state"];</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <pre>
   * The currently observed state. The underlying application
   * that is running can define this state
   * </pre>
   *
   * <code>string state = 1 [json_name = "state"];</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <pre>
   * Players that are currently connected or have been connected to the instance
   * </pre>
   *
   * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
   */
  java.util.List<network.cow.mooapis.instance.v1.Player> 
      getPlayersList();
  /**
   * <pre>
   * Players that are currently connected or have been connected to the instance
   * </pre>
   *
   * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
   */
  network.cow.mooapis.instance.v1.Player getPlayers(int index);
  /**
   * <pre>
   * Players that are currently connected or have been connected to the instance
   * </pre>
   *
   * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
   */
  int getPlayersCount();
  /**
   * <pre>
   * Players that are currently connected or have been connected to the instance
   * </pre>
   *
   * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
   */
  java.util.List<? extends network.cow.mooapis.instance.v1.PlayerOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <pre>
   * Players that are currently connected or have been connected to the instance
   * </pre>
   *
   * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
   */
  network.cow.mooapis.instance.v1.PlayerOrBuilder getPlayersOrBuilder(
      int index);
}
