// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/instance/v1/types.proto

package network.cow.mooapis.instance.v1;

/**
 * Protobuf type {@code cow.instance.v1.Metadata}
 */
public final class Metadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cow.instance.v1.Metadata)
    MetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Metadata.newBuilder() to construct.
  private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Metadata() {
    players_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Metadata();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Metadata(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Struct.Builder subBuilder = null;
            if (state_ != null) {
              subBuilder = state_.toBuilder();
            }
            state_ = input.readMessage(com.google.protobuf.Struct.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(state_);
              state_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              players_ = new java.util.ArrayList<network.cow.mooapis.instance.v1.Player>();
              mutable_bitField0_ |= 0x00000001;
            }
            players_.add(
                input.readMessage(network.cow.mooapis.instance.v1.Player.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        players_ = java.util.Collections.unmodifiableList(players_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return network.cow.mooapis.instance.v1.Types.internal_static_cow_instance_v1_Metadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return network.cow.mooapis.instance.v1.Types.internal_static_cow_instance_v1_Metadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            network.cow.mooapis.instance.v1.Metadata.class, network.cow.mooapis.instance.v1.Metadata.Builder.class);
  }

  public static final int STATE_FIELD_NUMBER = 1;
  private com.google.protobuf.Struct state_;
  /**
   * <pre>
   * The currently observed state. The underlying application
   * that is running can define this state
   * </pre>
   *
   * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
   * @return Whether the state field is set.
   */
  @java.lang.Override
  public boolean hasState() {
    return state_ != null;
  }
  /**
   * <pre>
   * The currently observed state. The underlying application
   * that is running can define this state
   * </pre>
   *
   * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
   * @return The state.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getState() {
    return state_ == null ? com.google.protobuf.Struct.getDefaultInstance() : state_;
  }
  /**
   * <pre>
   * The currently observed state. The underlying application
   * that is running can define this state
   * </pre>
   *
   * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getStateOrBuilder() {
    return getState();
  }

  public static final int PLAYERS_FIELD_NUMBER = 2;
  private java.util.List<network.cow.mooapis.instance.v1.Player> players_;
  /**
   * <pre>
   * Players that are currently connected or have been connected to the instance
   * </pre>
   *
   * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
   */
  @java.lang.Override
  public java.util.List<network.cow.mooapis.instance.v1.Player> getPlayersList() {
    return players_;
  }
  /**
   * <pre>
   * Players that are currently connected or have been connected to the instance
   * </pre>
   *
   * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends network.cow.mooapis.instance.v1.PlayerOrBuilder> 
      getPlayersOrBuilderList() {
    return players_;
  }
  /**
   * <pre>
   * Players that are currently connected or have been connected to the instance
   * </pre>
   *
   * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
   */
  @java.lang.Override
  public int getPlayersCount() {
    return players_.size();
  }
  /**
   * <pre>
   * Players that are currently connected or have been connected to the instance
   * </pre>
   *
   * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
   */
  @java.lang.Override
  public network.cow.mooapis.instance.v1.Player getPlayers(int index) {
    return players_.get(index);
  }
  /**
   * <pre>
   * Players that are currently connected or have been connected to the instance
   * </pre>
   *
   * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
   */
  @java.lang.Override
  public network.cow.mooapis.instance.v1.PlayerOrBuilder getPlayersOrBuilder(
      int index) {
    return players_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (state_ != null) {
      output.writeMessage(1, getState());
    }
    for (int i = 0; i < players_.size(); i++) {
      output.writeMessage(2, players_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (state_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getState());
    }
    for (int i = 0; i < players_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, players_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof network.cow.mooapis.instance.v1.Metadata)) {
      return super.equals(obj);
    }
    network.cow.mooapis.instance.v1.Metadata other = (network.cow.mooapis.instance.v1.Metadata) obj;

    if (hasState() != other.hasState()) return false;
    if (hasState()) {
      if (!getState()
          .equals(other.getState())) return false;
    }
    if (!getPlayersList()
        .equals(other.getPlayersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasState()) {
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
    }
    if (getPlayersCount() > 0) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static network.cow.mooapis.instance.v1.Metadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.instance.v1.Metadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(network.cow.mooapis.instance.v1.Metadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cow.instance.v1.Metadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cow.instance.v1.Metadata)
      network.cow.mooapis.instance.v1.MetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.cow.mooapis.instance.v1.Types.internal_static_cow_instance_v1_Metadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.cow.mooapis.instance.v1.Types.internal_static_cow_instance_v1_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.cow.mooapis.instance.v1.Metadata.class, network.cow.mooapis.instance.v1.Metadata.Builder.class);
    }

    // Construct using network.cow.mooapis.instance.v1.Metadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPlayersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (stateBuilder_ == null) {
        state_ = null;
      } else {
        state_ = null;
        stateBuilder_ = null;
      }
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        playersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return network.cow.mooapis.instance.v1.Types.internal_static_cow_instance_v1_Metadata_descriptor;
    }

    @java.lang.Override
    public network.cow.mooapis.instance.v1.Metadata getDefaultInstanceForType() {
      return network.cow.mooapis.instance.v1.Metadata.getDefaultInstance();
    }

    @java.lang.Override
    public network.cow.mooapis.instance.v1.Metadata build() {
      network.cow.mooapis.instance.v1.Metadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public network.cow.mooapis.instance.v1.Metadata buildPartial() {
      network.cow.mooapis.instance.v1.Metadata result = new network.cow.mooapis.instance.v1.Metadata(this);
      int from_bitField0_ = bitField0_;
      if (stateBuilder_ == null) {
        result.state_ = state_;
      } else {
        result.state_ = stateBuilder_.build();
      }
      if (playersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          players_ = java.util.Collections.unmodifiableList(players_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.players_ = players_;
      } else {
        result.players_ = playersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof network.cow.mooapis.instance.v1.Metadata) {
        return mergeFrom((network.cow.mooapis.instance.v1.Metadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(network.cow.mooapis.instance.v1.Metadata other) {
      if (other == network.cow.mooapis.instance.v1.Metadata.getDefaultInstance()) return this;
      if (other.hasState()) {
        mergeState(other.getState());
      }
      if (playersBuilder_ == null) {
        if (!other.players_.isEmpty()) {
          if (players_.isEmpty()) {
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePlayersIsMutable();
            players_.addAll(other.players_);
          }
          onChanged();
        }
      } else {
        if (!other.players_.isEmpty()) {
          if (playersBuilder_.isEmpty()) {
            playersBuilder_.dispose();
            playersBuilder_ = null;
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000001);
            playersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPlayersFieldBuilder() : null;
          } else {
            playersBuilder_.addAllMessages(other.players_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      network.cow.mooapis.instance.v1.Metadata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (network.cow.mooapis.instance.v1.Metadata) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Struct state_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> stateBuilder_;
    /**
     * <pre>
     * The currently observed state. The underlying application
     * that is running can define this state
     * </pre>
     *
     * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
     * @return Whether the state field is set.
     */
    public boolean hasState() {
      return stateBuilder_ != null || state_ != null;
    }
    /**
     * <pre>
     * The currently observed state. The underlying application
     * that is running can define this state
     * </pre>
     *
     * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
     * @return The state.
     */
    public com.google.protobuf.Struct getState() {
      if (stateBuilder_ == null) {
        return state_ == null ? com.google.protobuf.Struct.getDefaultInstance() : state_;
      } else {
        return stateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The currently observed state. The underlying application
     * that is running can define this state
     * </pre>
     *
     * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
     */
    public Builder setState(com.google.protobuf.Struct value) {
      if (stateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        state_ = value;
        onChanged();
      } else {
        stateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The currently observed state. The underlying application
     * that is running can define this state
     * </pre>
     *
     * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
     */
    public Builder setState(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (stateBuilder_ == null) {
        state_ = builderForValue.build();
        onChanged();
      } else {
        stateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The currently observed state. The underlying application
     * that is running can define this state
     * </pre>
     *
     * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
     */
    public Builder mergeState(com.google.protobuf.Struct value) {
      if (stateBuilder_ == null) {
        if (state_ != null) {
          state_ =
            com.google.protobuf.Struct.newBuilder(state_).mergeFrom(value).buildPartial();
        } else {
          state_ = value;
        }
        onChanged();
      } else {
        stateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The currently observed state. The underlying application
     * that is running can define this state
     * </pre>
     *
     * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
     */
    public Builder clearState() {
      if (stateBuilder_ == null) {
        state_ = null;
        onChanged();
      } else {
        state_ = null;
        stateBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The currently observed state. The underlying application
     * that is running can define this state
     * </pre>
     *
     * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
     */
    public com.google.protobuf.Struct.Builder getStateBuilder() {
      
      onChanged();
      return getStateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The currently observed state. The underlying application
     * that is running can define this state
     * </pre>
     *
     * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
     */
    public com.google.protobuf.StructOrBuilder getStateOrBuilder() {
      if (stateBuilder_ != null) {
        return stateBuilder_.getMessageOrBuilder();
      } else {
        return state_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : state_;
      }
    }
    /**
     * <pre>
     * The currently observed state. The underlying application
     * that is running can define this state
     * </pre>
     *
     * <code>.google.protobuf.Struct state = 1 [json_name = "state"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getStateFieldBuilder() {
      if (stateBuilder_ == null) {
        stateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getState(),
                getParentForChildren(),
                isClean());
        state_ = null;
      }
      return stateBuilder_;
    }

    private java.util.List<network.cow.mooapis.instance.v1.Player> players_ =
      java.util.Collections.emptyList();
    private void ensurePlayersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        players_ = new java.util.ArrayList<network.cow.mooapis.instance.v1.Player>(players_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        network.cow.mooapis.instance.v1.Player, network.cow.mooapis.instance.v1.Player.Builder, network.cow.mooapis.instance.v1.PlayerOrBuilder> playersBuilder_;

    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public java.util.List<network.cow.mooapis.instance.v1.Player> getPlayersList() {
      if (playersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(players_);
      } else {
        return playersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public int getPlayersCount() {
      if (playersBuilder_ == null) {
        return players_.size();
      } else {
        return playersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public network.cow.mooapis.instance.v1.Player getPlayers(int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);
      } else {
        return playersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public Builder setPlayers(
        int index, network.cow.mooapis.instance.v1.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.set(index, value);
        onChanged();
      } else {
        playersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public Builder setPlayers(
        int index, network.cow.mooapis.instance.v1.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.set(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public Builder addPlayers(network.cow.mooapis.instance.v1.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(value);
        onChanged();
      } else {
        playersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public Builder addPlayers(
        int index, network.cow.mooapis.instance.v1.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(index, value);
        onChanged();
      } else {
        playersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public Builder addPlayers(
        network.cow.mooapis.instance.v1.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public Builder addPlayers(
        int index, network.cow.mooapis.instance.v1.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public Builder addAllPlayers(
        java.lang.Iterable<? extends network.cow.mooapis.instance.v1.Player> values) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, players_);
        onChanged();
      } else {
        playersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public Builder clearPlayers() {
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        playersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public Builder removePlayers(int index) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.remove(index);
        onChanged();
      } else {
        playersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public network.cow.mooapis.instance.v1.Player.Builder getPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public network.cow.mooapis.instance.v1.PlayerOrBuilder getPlayersOrBuilder(
        int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);  } else {
        return playersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public java.util.List<? extends network.cow.mooapis.instance.v1.PlayerOrBuilder> 
         getPlayersOrBuilderList() {
      if (playersBuilder_ != null) {
        return playersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(players_);
      }
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public network.cow.mooapis.instance.v1.Player.Builder addPlayersBuilder() {
      return getPlayersFieldBuilder().addBuilder(
          network.cow.mooapis.instance.v1.Player.getDefaultInstance());
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public network.cow.mooapis.instance.v1.Player.Builder addPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().addBuilder(
          index, network.cow.mooapis.instance.v1.Player.getDefaultInstance());
    }
    /**
     * <pre>
     * Players that are currently connected or have been connected to the instance
     * </pre>
     *
     * <code>repeated .cow.instance.v1.Player players = 2 [json_name = "players"];</code>
     */
    public java.util.List<network.cow.mooapis.instance.v1.Player.Builder> 
         getPlayersBuilderList() {
      return getPlayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        network.cow.mooapis.instance.v1.Player, network.cow.mooapis.instance.v1.Player.Builder, network.cow.mooapis.instance.v1.PlayerOrBuilder> 
        getPlayersFieldBuilder() {
      if (playersBuilder_ == null) {
        playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            network.cow.mooapis.instance.v1.Player, network.cow.mooapis.instance.v1.Player.Builder, network.cow.mooapis.instance.v1.PlayerOrBuilder>(
                players_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        players_ = null;
      }
      return playersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cow.instance.v1.Metadata)
  }

  // @@protoc_insertion_point(class_scope:cow.instance.v1.Metadata)
  private static final network.cow.mooapis.instance.v1.Metadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new network.cow.mooapis.instance.v1.Metadata();
  }

  public static network.cow.mooapis.instance.v1.Metadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Metadata>
      PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
    @java.lang.Override
    public Metadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Metadata(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Metadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Metadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public network.cow.mooapis.instance.v1.Metadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

