// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/user/v1/user_service_api.proto

package network.cow.mooapis.user.v1;

public interface UpdatePlayerMetadataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.user.v1.UpdatePlayerMetadataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string player_id = 1 [json_name = "playerId"];</code>
   * @return The playerId.
   */
  java.lang.String getPlayerId();
  /**
   * <code>string player_id = 1 [json_name = "playerId"];</code>
   * @return The bytes for playerId.
   */
  com.google.protobuf.ByteString
      getPlayerIdBytes();

  /**
   * <code>string username = 2 [json_name = "username"];</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2 [json_name = "username"];</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>.cow.user.v1.Metadata metadata = 3 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.cow.user.v1.Metadata metadata = 3 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  network.cow.mooapis.user.v1.Metadata getMetadata();
  /**
   * <code>.cow.user.v1.Metadata metadata = 3 [json_name = "metadata"];</code>
   */
  network.cow.mooapis.user.v1.MetadataOrBuilder getMetadataOrBuilder();
}
