// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/user/v1/events.proto

package network.cow.mooapis.user.v1;

public interface UserMetadataUpdatedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.user.v1.UserMetadataUpdatedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>.cow.user.v1.Metadata metadata = 2 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.cow.user.v1.Metadata metadata = 2 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  network.cow.mooapis.user.v1.Metadata getMetadata();
  /**
   * <code>.cow.user.v1.Metadata metadata = 2 [json_name = "metadata"];</code>
   */
  network.cow.mooapis.user.v1.MetadataOrBuilder getMetadataOrBuilder();
}
