// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/indigo/v1/indigo.proto

package network.cow.mooapis.indigo.v1;

public interface AddUserRolesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.indigo.v1.AddUserRolesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_account_id = 1 [json_name = "userAccountId"];</code>
   * @return The userAccountId.
   */
  java.lang.String getUserAccountId();
  /**
   * <code>string user_account_id = 1 [json_name = "userAccountId"];</code>
   * @return The bytes for userAccountId.
   */
  com.google.protobuf.ByteString
      getUserAccountIdBytes();

  /**
   * <code>repeated .cow.indigo.v1.RoleIdentifier role_ids = 2 [json_name = "roleIds"];</code>
   */
  java.util.List<network.cow.mooapis.indigo.v1.RoleIdentifier> 
      getRoleIdsList();
  /**
   * <code>repeated .cow.indigo.v1.RoleIdentifier role_ids = 2 [json_name = "roleIds"];</code>
   */
  network.cow.mooapis.indigo.v1.RoleIdentifier getRoleIds(int index);
  /**
   * <code>repeated .cow.indigo.v1.RoleIdentifier role_ids = 2 [json_name = "roleIds"];</code>
   */
  int getRoleIdsCount();
  /**
   * <code>repeated .cow.indigo.v1.RoleIdentifier role_ids = 2 [json_name = "roleIds"];</code>
   */
  java.util.List<? extends network.cow.mooapis.indigo.v1.RoleIdentifierOrBuilder> 
      getRoleIdsOrBuilderList();
  /**
   * <code>repeated .cow.indigo.v1.RoleIdentifier role_ids = 2 [json_name = "roleIds"];</code>
   */
  network.cow.mooapis.indigo.v1.RoleIdentifierOrBuilder getRoleIdsOrBuilder(
      int index);
}
