// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/indigo/v1/indigo.proto

package network.cow.mooapis.indigo.v1;

public interface DeleteRoleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.indigo.v1.DeleteRoleResponse)
    com.google.protobuf.MessageOrBuilder {
}
