// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/indigo/v1/indigo.proto

package network.cow.mooapis.indigo.v1;

public interface HasUserPermissionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.indigo.v1.HasUserPermissionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1 [json_name = "result"];</code>
   * @return The result.
   */
  boolean getResult();
}
