// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/indigo/v1/events.proto

package network.cow.mooapis.indigo.v1;

public interface RoleUpdateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.indigo.v1.RoleUpdateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cow.indigo.v1.Role role = 1 [json_name = "role"];</code>
   * @return Whether the role field is set.
   */
  boolean hasRole();
  /**
   * <code>.cow.indigo.v1.Role role = 1 [json_name = "role"];</code>
   * @return The role.
   */
  network.cow.mooapis.indigo.v1.Role getRole();
  /**
   * <code>.cow.indigo.v1.Role role = 1 [json_name = "role"];</code>
   */
  network.cow.mooapis.indigo.v1.RoleOrBuilder getRoleOrBuilder();

  /**
   * <code>.cow.indigo.v1.RoleUpdateEvent.Action action = 2 [json_name = "action"];</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.cow.indigo.v1.RoleUpdateEvent.Action action = 2 [json_name = "action"];</code>
   * @return The action.
   */
  network.cow.mooapis.indigo.v1.RoleUpdateEvent.Action getAction();
}
