// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/indigo/v1/indigo.proto

package network.cow.mooapis.indigo.v1;

/**
 * Protobuf type {@code cow.indigo.v1.RoleIdentifier}
 */
public final class RoleIdentifier extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cow.indigo.v1.RoleIdentifier)
    RoleIdentifierOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RoleIdentifier.newBuilder() to construct.
  private RoleIdentifier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RoleIdentifier() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RoleIdentifier();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RoleIdentifier(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            idCase_ = 1;
            id_ = s;
            break;
          }
          case 18: {
            network.cow.mooapis.indigo.v1.RoleNameIdentifier.Builder subBuilder = null;
            if (idCase_ == 2) {
              subBuilder = ((network.cow.mooapis.indigo.v1.RoleNameIdentifier) id_).toBuilder();
            }
            id_ =
                input.readMessage(network.cow.mooapis.indigo.v1.RoleNameIdentifier.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((network.cow.mooapis.indigo.v1.RoleNameIdentifier) id_);
              id_ = subBuilder.buildPartial();
            }
            idCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return network.cow.mooapis.indigo.v1.Indigo.internal_static_cow_indigo_v1_RoleIdentifier_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return network.cow.mooapis.indigo.v1.Indigo.internal_static_cow_indigo_v1_RoleIdentifier_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            network.cow.mooapis.indigo.v1.RoleIdentifier.class, network.cow.mooapis.indigo.v1.RoleIdentifier.Builder.class);
  }

  private int idCase_ = 0;
  private java.lang.Object id_;
  public enum IdCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    UUID(1),
    NAME_ID(2),
    ID_NOT_SET(0);
    private final int value;
    private IdCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static IdCase valueOf(int value) {
      return forNumber(value);
    }

    public static IdCase forNumber(int value) {
      switch (value) {
        case 1: return UUID;
        case 2: return NAME_ID;
        case 0: return ID_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public IdCase
  getIdCase() {
    return IdCase.forNumber(
        idCase_);
  }

  public static final int UUID_FIELD_NUMBER = 1;
  /**
   * <code>string uuid = 1 [json_name = "uuid"];</code>
   * @return Whether the uuid field is set.
   */
  public boolean hasUuid() {
    return idCase_ == 1;
  }
  /**
   * <code>string uuid = 1 [json_name = "uuid"];</code>
   * @return The uuid.
   */
  public java.lang.String getUuid() {
    java.lang.Object ref = "";
    if (idCase_ == 1) {
      ref = id_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (idCase_ == 1) {
        id_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string uuid = 1 [json_name = "uuid"];</code>
   * @return The bytes for uuid.
   */
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = "";
    if (idCase_ == 1) {
      ref = id_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (idCase_ == 1) {
        id_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_ID_FIELD_NUMBER = 2;
  /**
   * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
   * @return Whether the nameId field is set.
   */
  @java.lang.Override
  public boolean hasNameId() {
    return idCase_ == 2;
  }
  /**
   * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
   * @return The nameId.
   */
  @java.lang.Override
  public network.cow.mooapis.indigo.v1.RoleNameIdentifier getNameId() {
    if (idCase_ == 2) {
       return (network.cow.mooapis.indigo.v1.RoleNameIdentifier) id_;
    }
    return network.cow.mooapis.indigo.v1.RoleNameIdentifier.getDefaultInstance();
  }
  /**
   * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
   */
  @java.lang.Override
  public network.cow.mooapis.indigo.v1.RoleNameIdentifierOrBuilder getNameIdOrBuilder() {
    if (idCase_ == 2) {
       return (network.cow.mooapis.indigo.v1.RoleNameIdentifier) id_;
    }
    return network.cow.mooapis.indigo.v1.RoleNameIdentifier.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idCase_ == 1) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (idCase_ == 2) {
      output.writeMessage(2, (network.cow.mooapis.indigo.v1.RoleNameIdentifier) id_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idCase_ == 1) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (idCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (network.cow.mooapis.indigo.v1.RoleNameIdentifier) id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof network.cow.mooapis.indigo.v1.RoleIdentifier)) {
      return super.equals(obj);
    }
    network.cow.mooapis.indigo.v1.RoleIdentifier other = (network.cow.mooapis.indigo.v1.RoleIdentifier) obj;

    if (!getIdCase().equals(other.getIdCase())) return false;
    switch (idCase_) {
      case 1:
        if (!getUuid()
            .equals(other.getUuid())) return false;
        break;
      case 2:
        if (!getNameId()
            .equals(other.getNameId())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (idCase_) {
      case 1:
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
        break;
      case 2:
        hash = (37 * hash) + NAME_ID_FIELD_NUMBER;
        hash = (53 * hash) + getNameId().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.indigo.v1.RoleIdentifier parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(network.cow.mooapis.indigo.v1.RoleIdentifier prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cow.indigo.v1.RoleIdentifier}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cow.indigo.v1.RoleIdentifier)
      network.cow.mooapis.indigo.v1.RoleIdentifierOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.cow.mooapis.indigo.v1.Indigo.internal_static_cow_indigo_v1_RoleIdentifier_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.cow.mooapis.indigo.v1.Indigo.internal_static_cow_indigo_v1_RoleIdentifier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.cow.mooapis.indigo.v1.RoleIdentifier.class, network.cow.mooapis.indigo.v1.RoleIdentifier.Builder.class);
    }

    // Construct using network.cow.mooapis.indigo.v1.RoleIdentifier.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idCase_ = 0;
      id_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return network.cow.mooapis.indigo.v1.Indigo.internal_static_cow_indigo_v1_RoleIdentifier_descriptor;
    }

    @java.lang.Override
    public network.cow.mooapis.indigo.v1.RoleIdentifier getDefaultInstanceForType() {
      return network.cow.mooapis.indigo.v1.RoleIdentifier.getDefaultInstance();
    }

    @java.lang.Override
    public network.cow.mooapis.indigo.v1.RoleIdentifier build() {
      network.cow.mooapis.indigo.v1.RoleIdentifier result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public network.cow.mooapis.indigo.v1.RoleIdentifier buildPartial() {
      network.cow.mooapis.indigo.v1.RoleIdentifier result = new network.cow.mooapis.indigo.v1.RoleIdentifier(this);
      if (idCase_ == 1) {
        result.id_ = id_;
      }
      if (idCase_ == 2) {
        if (nameIdBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = nameIdBuilder_.build();
        }
      }
      result.idCase_ = idCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof network.cow.mooapis.indigo.v1.RoleIdentifier) {
        return mergeFrom((network.cow.mooapis.indigo.v1.RoleIdentifier)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(network.cow.mooapis.indigo.v1.RoleIdentifier other) {
      if (other == network.cow.mooapis.indigo.v1.RoleIdentifier.getDefaultInstance()) return this;
      switch (other.getIdCase()) {
        case UUID: {
          idCase_ = 1;
          id_ = other.id_;
          onChanged();
          break;
        }
        case NAME_ID: {
          mergeNameId(other.getNameId());
          break;
        }
        case ID_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      network.cow.mooapis.indigo.v1.RoleIdentifier parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (network.cow.mooapis.indigo.v1.RoleIdentifier) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int idCase_ = 0;
    private java.lang.Object id_;
    public IdCase
        getIdCase() {
      return IdCase.forNumber(
          idCase_);
    }

    public Builder clearId() {
      idCase_ = 0;
      id_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>string uuid = 1 [json_name = "uuid"];</code>
     * @return Whether the uuid field is set.
     */
    @java.lang.Override
    public boolean hasUuid() {
      return idCase_ == 1;
    }
    /**
     * <code>string uuid = 1 [json_name = "uuid"];</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      java.lang.Object ref = "";
      if (idCase_ == 1) {
        ref = id_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (idCase_ == 1) {
          id_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 1 [json_name = "uuid"];</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = "";
      if (idCase_ == 1) {
        ref = id_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (idCase_ == 1) {
          id_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 1 [json_name = "uuid"];</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  idCase_ = 1;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 1 [json_name = "uuid"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      if (idCase_ == 1) {
        idCase_ = 0;
        id_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string uuid = 1 [json_name = "uuid"];</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      idCase_ = 1;
      id_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.mooapis.indigo.v1.RoleNameIdentifier, network.cow.mooapis.indigo.v1.RoleNameIdentifier.Builder, network.cow.mooapis.indigo.v1.RoleNameIdentifierOrBuilder> nameIdBuilder_;
    /**
     * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
     * @return Whether the nameId field is set.
     */
    @java.lang.Override
    public boolean hasNameId() {
      return idCase_ == 2;
    }
    /**
     * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
     * @return The nameId.
     */
    @java.lang.Override
    public network.cow.mooapis.indigo.v1.RoleNameIdentifier getNameId() {
      if (nameIdBuilder_ == null) {
        if (idCase_ == 2) {
          return (network.cow.mooapis.indigo.v1.RoleNameIdentifier) id_;
        }
        return network.cow.mooapis.indigo.v1.RoleNameIdentifier.getDefaultInstance();
      } else {
        if (idCase_ == 2) {
          return nameIdBuilder_.getMessage();
        }
        return network.cow.mooapis.indigo.v1.RoleNameIdentifier.getDefaultInstance();
      }
    }
    /**
     * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
     */
    public Builder setNameId(network.cow.mooapis.indigo.v1.RoleNameIdentifier value) {
      if (nameIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        nameIdBuilder_.setMessage(value);
      }
      idCase_ = 2;
      return this;
    }
    /**
     * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
     */
    public Builder setNameId(
        network.cow.mooapis.indigo.v1.RoleNameIdentifier.Builder builderForValue) {
      if (nameIdBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        nameIdBuilder_.setMessage(builderForValue.build());
      }
      idCase_ = 2;
      return this;
    }
    /**
     * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
     */
    public Builder mergeNameId(network.cow.mooapis.indigo.v1.RoleNameIdentifier value) {
      if (nameIdBuilder_ == null) {
        if (idCase_ == 2 &&
            id_ != network.cow.mooapis.indigo.v1.RoleNameIdentifier.getDefaultInstance()) {
          id_ = network.cow.mooapis.indigo.v1.RoleNameIdentifier.newBuilder((network.cow.mooapis.indigo.v1.RoleNameIdentifier) id_)
              .mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        if (idCase_ == 2) {
          nameIdBuilder_.mergeFrom(value);
        }
        nameIdBuilder_.setMessage(value);
      }
      idCase_ = 2;
      return this;
    }
    /**
     * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
     */
    public Builder clearNameId() {
      if (nameIdBuilder_ == null) {
        if (idCase_ == 2) {
          idCase_ = 0;
          id_ = null;
          onChanged();
        }
      } else {
        if (idCase_ == 2) {
          idCase_ = 0;
          id_ = null;
        }
        nameIdBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
     */
    public network.cow.mooapis.indigo.v1.RoleNameIdentifier.Builder getNameIdBuilder() {
      return getNameIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
     */
    @java.lang.Override
    public network.cow.mooapis.indigo.v1.RoleNameIdentifierOrBuilder getNameIdOrBuilder() {
      if ((idCase_ == 2) && (nameIdBuilder_ != null)) {
        return nameIdBuilder_.getMessageOrBuilder();
      } else {
        if (idCase_ == 2) {
          return (network.cow.mooapis.indigo.v1.RoleNameIdentifier) id_;
        }
        return network.cow.mooapis.indigo.v1.RoleNameIdentifier.getDefaultInstance();
      }
    }
    /**
     * <code>.cow.indigo.v1.RoleNameIdentifier name_id = 2 [json_name = "nameId"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.mooapis.indigo.v1.RoleNameIdentifier, network.cow.mooapis.indigo.v1.RoleNameIdentifier.Builder, network.cow.mooapis.indigo.v1.RoleNameIdentifierOrBuilder> 
        getNameIdFieldBuilder() {
      if (nameIdBuilder_ == null) {
        if (!(idCase_ == 2)) {
          id_ = network.cow.mooapis.indigo.v1.RoleNameIdentifier.getDefaultInstance();
        }
        nameIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.mooapis.indigo.v1.RoleNameIdentifier, network.cow.mooapis.indigo.v1.RoleNameIdentifier.Builder, network.cow.mooapis.indigo.v1.RoleNameIdentifierOrBuilder>(
                (network.cow.mooapis.indigo.v1.RoleNameIdentifier) id_,
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      idCase_ = 2;
      onChanged();;
      return nameIdBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cow.indigo.v1.RoleIdentifier)
  }

  // @@protoc_insertion_point(class_scope:cow.indigo.v1.RoleIdentifier)
  private static final network.cow.mooapis.indigo.v1.RoleIdentifier DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new network.cow.mooapis.indigo.v1.RoleIdentifier();
  }

  public static network.cow.mooapis.indigo.v1.RoleIdentifier getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoleIdentifier>
      PARSER = new com.google.protobuf.AbstractParser<RoleIdentifier>() {
    @java.lang.Override
    public RoleIdentifier parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RoleIdentifier(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RoleIdentifier> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RoleIdentifier> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public network.cow.mooapis.indigo.v1.RoleIdentifier getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

