// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/indigo/v1/indigo.proto

package network.cow.mooapis.indigo.v1;

/**
 * Protobuf type {@code cow.indigo.v1.User}
 */
public final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cow.indigo.v1.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    accountId_ = "";
    roles_ = java.util.Collections.emptyList();
    customPermissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new User();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accountId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              roles_ = new java.util.ArrayList<network.cow.mooapis.indigo.v1.Role>();
              mutable_bitField0_ |= 0x00000001;
            }
            roles_.add(
                input.readMessage(network.cow.mooapis.indigo.v1.Role.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              customPermissions_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            customPermissions_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        roles_ = java.util.Collections.unmodifiableList(roles_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        customPermissions_ = customPermissions_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return network.cow.mooapis.indigo.v1.Indigo.internal_static_cow_indigo_v1_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return network.cow.mooapis.indigo.v1.Indigo.internal_static_cow_indigo_v1_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            network.cow.mooapis.indigo.v1.User.class, network.cow.mooapis.indigo.v1.User.Builder.class);
  }

  public static final int ACCOUNT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object accountId_;
  /**
   * <pre>
   * The id of the user, can be a UUID or some other kind of string.
   * </pre>
   *
   * <code>string account_id = 1 [json_name = "accountId"];</code>
   * @return The accountId.
   */
  @java.lang.Override
  public java.lang.String getAccountId() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The id of the user, can be a UUID or some other kind of string.
   * </pre>
   *
   * <code>string account_id = 1 [json_name = "accountId"];</code>
   * @return The bytes for accountId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccountIdBytes() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLES_FIELD_NUMBER = 2;
  private java.util.List<network.cow.mooapis.indigo.v1.Role> roles_;
  /**
   * <pre>
   * All roles that are bound to the user.
   * </pre>
   *
   * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
   */
  @java.lang.Override
  public java.util.List<network.cow.mooapis.indigo.v1.Role> getRolesList() {
    return roles_;
  }
  /**
   * <pre>
   * All roles that are bound to the user.
   * </pre>
   *
   * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends network.cow.mooapis.indigo.v1.RoleOrBuilder> 
      getRolesOrBuilderList() {
    return roles_;
  }
  /**
   * <pre>
   * All roles that are bound to the user.
   * </pre>
   *
   * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
   */
  @java.lang.Override
  public int getRolesCount() {
    return roles_.size();
  }
  /**
   * <pre>
   * All roles that are bound to the user.
   * </pre>
   *
   * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
   */
  @java.lang.Override
  public network.cow.mooapis.indigo.v1.Role getRoles(int index) {
    return roles_.get(index);
  }
  /**
   * <pre>
   * All roles that are bound to the user.
   * </pre>
   *
   * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
   */
  @java.lang.Override
  public network.cow.mooapis.indigo.v1.RoleOrBuilder getRolesOrBuilder(
      int index) {
    return roles_.get(index);
  }

  public static final int CUSTOM_PERMISSIONS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList customPermissions_;
  /**
   * <pre>
   * All custom permissions that are bound to the user.
   * </pre>
   *
   * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
   * @return A list containing the customPermissions.
   */
  public com.google.protobuf.ProtocolStringList
      getCustomPermissionsList() {
    return customPermissions_;
  }
  /**
   * <pre>
   * All custom permissions that are bound to the user.
   * </pre>
   *
   * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
   * @return The count of customPermissions.
   */
  public int getCustomPermissionsCount() {
    return customPermissions_.size();
  }
  /**
   * <pre>
   * All custom permissions that are bound to the user.
   * </pre>
   *
   * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
   * @param index The index of the element to return.
   * @return The customPermissions at the given index.
   */
  public java.lang.String getCustomPermissions(int index) {
    return customPermissions_.get(index);
  }
  /**
   * <pre>
   * All custom permissions that are bound to the user.
   * </pre>
   *
   * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the customPermissions at the given index.
   */
  public com.google.protobuf.ByteString
      getCustomPermissionsBytes(int index) {
    return customPermissions_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccountIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountId_);
    }
    for (int i = 0; i < roles_.size(); i++) {
      output.writeMessage(2, roles_.get(i));
    }
    for (int i = 0; i < customPermissions_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, customPermissions_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccountIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountId_);
    }
    for (int i = 0; i < roles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, roles_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < customPermissions_.size(); i++) {
        dataSize += computeStringSizeNoTag(customPermissions_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCustomPermissionsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof network.cow.mooapis.indigo.v1.User)) {
      return super.equals(obj);
    }
    network.cow.mooapis.indigo.v1.User other = (network.cow.mooapis.indigo.v1.User) obj;

    if (!getAccountId()
        .equals(other.getAccountId())) return false;
    if (!getRolesList()
        .equals(other.getRolesList())) return false;
    if (!getCustomPermissionsList()
        .equals(other.getCustomPermissionsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId().hashCode();
    if (getRolesCount() > 0) {
      hash = (37 * hash) + ROLES_FIELD_NUMBER;
      hash = (53 * hash) + getRolesList().hashCode();
    }
    if (getCustomPermissionsCount() > 0) {
      hash = (37 * hash) + CUSTOM_PERMISSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getCustomPermissionsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static network.cow.mooapis.indigo.v1.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.indigo.v1.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.indigo.v1.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.indigo.v1.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.indigo.v1.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.indigo.v1.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.indigo.v1.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.indigo.v1.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.mooapis.indigo.v1.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.indigo.v1.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.mooapis.indigo.v1.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.indigo.v1.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(network.cow.mooapis.indigo.v1.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cow.indigo.v1.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cow.indigo.v1.User)
      network.cow.mooapis.indigo.v1.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.cow.mooapis.indigo.v1.Indigo.internal_static_cow_indigo_v1_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.cow.mooapis.indigo.v1.Indigo.internal_static_cow_indigo_v1_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.cow.mooapis.indigo.v1.User.class, network.cow.mooapis.indigo.v1.User.Builder.class);
    }

    // Construct using network.cow.mooapis.indigo.v1.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRolesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      accountId_ = "";

      if (rolesBuilder_ == null) {
        roles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        rolesBuilder_.clear();
      }
      customPermissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return network.cow.mooapis.indigo.v1.Indigo.internal_static_cow_indigo_v1_User_descriptor;
    }

    @java.lang.Override
    public network.cow.mooapis.indigo.v1.User getDefaultInstanceForType() {
      return network.cow.mooapis.indigo.v1.User.getDefaultInstance();
    }

    @java.lang.Override
    public network.cow.mooapis.indigo.v1.User build() {
      network.cow.mooapis.indigo.v1.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public network.cow.mooapis.indigo.v1.User buildPartial() {
      network.cow.mooapis.indigo.v1.User result = new network.cow.mooapis.indigo.v1.User(this);
      int from_bitField0_ = bitField0_;
      result.accountId_ = accountId_;
      if (rolesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          roles_ = java.util.Collections.unmodifiableList(roles_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.roles_ = roles_;
      } else {
        result.roles_ = rolesBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        customPermissions_ = customPermissions_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.customPermissions_ = customPermissions_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof network.cow.mooapis.indigo.v1.User) {
        return mergeFrom((network.cow.mooapis.indigo.v1.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(network.cow.mooapis.indigo.v1.User other) {
      if (other == network.cow.mooapis.indigo.v1.User.getDefaultInstance()) return this;
      if (!other.getAccountId().isEmpty()) {
        accountId_ = other.accountId_;
        onChanged();
      }
      if (rolesBuilder_ == null) {
        if (!other.roles_.isEmpty()) {
          if (roles_.isEmpty()) {
            roles_ = other.roles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRolesIsMutable();
            roles_.addAll(other.roles_);
          }
          onChanged();
        }
      } else {
        if (!other.roles_.isEmpty()) {
          if (rolesBuilder_.isEmpty()) {
            rolesBuilder_.dispose();
            rolesBuilder_ = null;
            roles_ = other.roles_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rolesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRolesFieldBuilder() : null;
          } else {
            rolesBuilder_.addAllMessages(other.roles_);
          }
        }
      }
      if (!other.customPermissions_.isEmpty()) {
        if (customPermissions_.isEmpty()) {
          customPermissions_ = other.customPermissions_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureCustomPermissionsIsMutable();
          customPermissions_.addAll(other.customPermissions_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      network.cow.mooapis.indigo.v1.User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (network.cow.mooapis.indigo.v1.User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object accountId_ = "";
    /**
     * <pre>
     * The id of the user, can be a UUID or some other kind of string.
     * </pre>
     *
     * <code>string account_id = 1 [json_name = "accountId"];</code>
     * @return The accountId.
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The id of the user, can be a UUID or some other kind of string.
     * </pre>
     *
     * <code>string account_id = 1 [json_name = "accountId"];</code>
     * @return The bytes for accountId.
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The id of the user, can be a UUID or some other kind of string.
     * </pre>
     *
     * <code>string account_id = 1 [json_name = "accountId"];</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the user, can be a UUID or some other kind of string.
     * </pre>
     *
     * <code>string account_id = 1 [json_name = "accountId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      
      accountId_ = getDefaultInstance().getAccountId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The id of the user, can be a UUID or some other kind of string.
     * </pre>
     *
     * <code>string account_id = 1 [json_name = "accountId"];</code>
     * @param value The bytes for accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<network.cow.mooapis.indigo.v1.Role> roles_ =
      java.util.Collections.emptyList();
    private void ensureRolesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        roles_ = new java.util.ArrayList<network.cow.mooapis.indigo.v1.Role>(roles_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        network.cow.mooapis.indigo.v1.Role, network.cow.mooapis.indigo.v1.Role.Builder, network.cow.mooapis.indigo.v1.RoleOrBuilder> rolesBuilder_;

    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public java.util.List<network.cow.mooapis.indigo.v1.Role> getRolesList() {
      if (rolesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(roles_);
      } else {
        return rolesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public int getRolesCount() {
      if (rolesBuilder_ == null) {
        return roles_.size();
      } else {
        return rolesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public network.cow.mooapis.indigo.v1.Role getRoles(int index) {
      if (rolesBuilder_ == null) {
        return roles_.get(index);
      } else {
        return rolesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public Builder setRoles(
        int index, network.cow.mooapis.indigo.v1.Role value) {
      if (rolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRolesIsMutable();
        roles_.set(index, value);
        onChanged();
      } else {
        rolesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public Builder setRoles(
        int index, network.cow.mooapis.indigo.v1.Role.Builder builderForValue) {
      if (rolesBuilder_ == null) {
        ensureRolesIsMutable();
        roles_.set(index, builderForValue.build());
        onChanged();
      } else {
        rolesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public Builder addRoles(network.cow.mooapis.indigo.v1.Role value) {
      if (rolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRolesIsMutable();
        roles_.add(value);
        onChanged();
      } else {
        rolesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public Builder addRoles(
        int index, network.cow.mooapis.indigo.v1.Role value) {
      if (rolesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRolesIsMutable();
        roles_.add(index, value);
        onChanged();
      } else {
        rolesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public Builder addRoles(
        network.cow.mooapis.indigo.v1.Role.Builder builderForValue) {
      if (rolesBuilder_ == null) {
        ensureRolesIsMutable();
        roles_.add(builderForValue.build());
        onChanged();
      } else {
        rolesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public Builder addRoles(
        int index, network.cow.mooapis.indigo.v1.Role.Builder builderForValue) {
      if (rolesBuilder_ == null) {
        ensureRolesIsMutable();
        roles_.add(index, builderForValue.build());
        onChanged();
      } else {
        rolesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public Builder addAllRoles(
        java.lang.Iterable<? extends network.cow.mooapis.indigo.v1.Role> values) {
      if (rolesBuilder_ == null) {
        ensureRolesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roles_);
        onChanged();
      } else {
        rolesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public Builder clearRoles() {
      if (rolesBuilder_ == null) {
        roles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rolesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public Builder removeRoles(int index) {
      if (rolesBuilder_ == null) {
        ensureRolesIsMutable();
        roles_.remove(index);
        onChanged();
      } else {
        rolesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public network.cow.mooapis.indigo.v1.Role.Builder getRolesBuilder(
        int index) {
      return getRolesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public network.cow.mooapis.indigo.v1.RoleOrBuilder getRolesOrBuilder(
        int index) {
      if (rolesBuilder_ == null) {
        return roles_.get(index);  } else {
        return rolesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public java.util.List<? extends network.cow.mooapis.indigo.v1.RoleOrBuilder> 
         getRolesOrBuilderList() {
      if (rolesBuilder_ != null) {
        return rolesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(roles_);
      }
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public network.cow.mooapis.indigo.v1.Role.Builder addRolesBuilder() {
      return getRolesFieldBuilder().addBuilder(
          network.cow.mooapis.indigo.v1.Role.getDefaultInstance());
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public network.cow.mooapis.indigo.v1.Role.Builder addRolesBuilder(
        int index) {
      return getRolesFieldBuilder().addBuilder(
          index, network.cow.mooapis.indigo.v1.Role.getDefaultInstance());
    }
    /**
     * <pre>
     * All roles that are bound to the user.
     * </pre>
     *
     * <code>repeated .cow.indigo.v1.Role roles = 2 [json_name = "roles"];</code>
     */
    public java.util.List<network.cow.mooapis.indigo.v1.Role.Builder> 
         getRolesBuilderList() {
      return getRolesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        network.cow.mooapis.indigo.v1.Role, network.cow.mooapis.indigo.v1.Role.Builder, network.cow.mooapis.indigo.v1.RoleOrBuilder> 
        getRolesFieldBuilder() {
      if (rolesBuilder_ == null) {
        rolesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            network.cow.mooapis.indigo.v1.Role, network.cow.mooapis.indigo.v1.Role.Builder, network.cow.mooapis.indigo.v1.RoleOrBuilder>(
                roles_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        roles_ = null;
      }
      return rolesBuilder_;
    }

    private com.google.protobuf.LazyStringList customPermissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCustomPermissionsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        customPermissions_ = new com.google.protobuf.LazyStringArrayList(customPermissions_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * All custom permissions that are bound to the user.
     * </pre>
     *
     * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
     * @return A list containing the customPermissions.
     */
    public com.google.protobuf.ProtocolStringList
        getCustomPermissionsList() {
      return customPermissions_.getUnmodifiableView();
    }
    /**
     * <pre>
     * All custom permissions that are bound to the user.
     * </pre>
     *
     * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
     * @return The count of customPermissions.
     */
    public int getCustomPermissionsCount() {
      return customPermissions_.size();
    }
    /**
     * <pre>
     * All custom permissions that are bound to the user.
     * </pre>
     *
     * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
     * @param index The index of the element to return.
     * @return The customPermissions at the given index.
     */
    public java.lang.String getCustomPermissions(int index) {
      return customPermissions_.get(index);
    }
    /**
     * <pre>
     * All custom permissions that are bound to the user.
     * </pre>
     *
     * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the customPermissions at the given index.
     */
    public com.google.protobuf.ByteString
        getCustomPermissionsBytes(int index) {
      return customPermissions_.getByteString(index);
    }
    /**
     * <pre>
     * All custom permissions that are bound to the user.
     * </pre>
     *
     * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
     * @param index The index to set the value at.
     * @param value The customPermissions to set.
     * @return This builder for chaining.
     */
    public Builder setCustomPermissions(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomPermissionsIsMutable();
      customPermissions_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All custom permissions that are bound to the user.
     * </pre>
     *
     * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
     * @param value The customPermissions to add.
     * @return This builder for chaining.
     */
    public Builder addCustomPermissions(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomPermissionsIsMutable();
      customPermissions_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All custom permissions that are bound to the user.
     * </pre>
     *
     * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
     * @param values The customPermissions to add.
     * @return This builder for chaining.
     */
    public Builder addAllCustomPermissions(
        java.lang.Iterable<java.lang.String> values) {
      ensureCustomPermissionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, customPermissions_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All custom permissions that are bound to the user.
     * </pre>
     *
     * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomPermissions() {
      customPermissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * All custom permissions that are bound to the user.
     * </pre>
     *
     * <code>repeated string custom_permissions = 3 [json_name = "customPermissions"];</code>
     * @param value The bytes of the customPermissions to add.
     * @return This builder for chaining.
     */
    public Builder addCustomPermissionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCustomPermissionsIsMutable();
      customPermissions_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cow.indigo.v1.User)
  }

  // @@protoc_insertion_point(class_scope:cow.indigo.v1.User)
  private static final network.cow.mooapis.indigo.v1.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new network.cow.mooapis.indigo.v1.User();
  }

  public static network.cow.mooapis.indigo.v1.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public network.cow.mooapis.indigo.v1.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

