// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/session/v1/session_service_api.proto

package network.cow.mooapis.session.v1;

public interface CreateSessionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.session.v1.CreateSessionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The session created by this service.
   * </pre>
   *
   * <code>.cow.session.v1.Session session = 1 [json_name = "session"];</code>
   * @return Whether the session field is set.
   */
  boolean hasSession();
  /**
   * <pre>
   * The session created by this service.
   * </pre>
   *
   * <code>.cow.session.v1.Session session = 1 [json_name = "session"];</code>
   * @return The session.
   */
  network.cow.mooapis.session.v1.Session getSession();
  /**
   * <pre>
   * The session created by this service.
   * </pre>
   *
   * <code>.cow.session.v1.Session session = 1 [json_name = "session"];</code>
   */
  network.cow.mooapis.session.v1.SessionOrBuilder getSessionOrBuilder();
}
