// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/session/v1/types.proto

package network.cow.mooapis.session.v1;

public interface ExecutorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.session.v1.Executor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The globally unique identifier of the executor (e.g. user id or host name).
   * </pre>
   *
   * <code>string identifier = 1 [json_name = "identifier"];</code>
   * @return Whether the identifier field is set.
   */
  boolean hasIdentifier();
  /**
   * <pre>
   * The globally unique identifier of the executor (e.g. user id or host name).
   * </pre>
   *
   * <code>string identifier = 1 [json_name = "identifier"];</code>
   * @return The identifier.
   */
  java.lang.String getIdentifier();
  /**
   * <pre>
   * The globally unique identifier of the executor (e.g. user id or host name).
   * </pre>
   *
   * <code>string identifier = 1 [json_name = "identifier"];</code>
   * @return The bytes for identifier.
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();

  /**
   * <pre>
   * The executing player.
   * </pre>
   *
   * <code>string player_id = 2 [json_name = "playerId"];</code>
   * @return Whether the playerId field is set.
   */
  boolean hasPlayerId();
  /**
   * <pre>
   * The executing player.
   * </pre>
   *
   * <code>string player_id = 2 [json_name = "playerId"];</code>
   * @return The playerId.
   */
  java.lang.String getPlayerId();
  /**
   * <pre>
   * The executing player.
   * </pre>
   *
   * <code>string player_id = 2 [json_name = "playerId"];</code>
   * @return The bytes for playerId.
   */
  com.google.protobuf.ByteString
      getPlayerIdBytes();

  public network.cow.mooapis.session.v1.Executor.ExecutorCase getExecutorCase();
}
