// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/session/v1/session_service_api.proto

package network.cow.mooapis.session.v1;

public interface KickPlayerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.session.v1.KickPlayerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The resulting kick.
   * </pre>
   *
   * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
   * @return Whether the kick field is set.
   */
  boolean hasKick();
  /**
   * <pre>
   * The resulting kick.
   * </pre>
   *
   * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
   * @return The kick.
   */
  network.cow.mooapis.session.v1.Kick getKick();
  /**
   * <pre>
   * The resulting kick.
   * </pre>
   *
   * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
   */
  network.cow.mooapis.session.v1.KickOrBuilder getKickOrBuilder();
}
