// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/session/v1/session_service_api.proto

package network.cow.mooapis.session.v1;

/**
 * Protobuf type {@code cow.session.v1.KickPlayerResponse}
 */
public final class KickPlayerResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cow.session.v1.KickPlayerResponse)
    KickPlayerResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KickPlayerResponse.newBuilder() to construct.
  private KickPlayerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KickPlayerResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KickPlayerResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KickPlayerResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            network.cow.mooapis.session.v1.Kick.Builder subBuilder = null;
            if (kick_ != null) {
              subBuilder = kick_.toBuilder();
            }
            kick_ = input.readMessage(network.cow.mooapis.session.v1.Kick.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(kick_);
              kick_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return network.cow.mooapis.session.v1.SessionServiceApi.internal_static_cow_session_v1_KickPlayerResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return network.cow.mooapis.session.v1.SessionServiceApi.internal_static_cow_session_v1_KickPlayerResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            network.cow.mooapis.session.v1.KickPlayerResponse.class, network.cow.mooapis.session.v1.KickPlayerResponse.Builder.class);
  }

  public static final int KICK_FIELD_NUMBER = 1;
  private network.cow.mooapis.session.v1.Kick kick_;
  /**
   * <pre>
   * The resulting kick.
   * </pre>
   *
   * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
   * @return Whether the kick field is set.
   */
  @java.lang.Override
  public boolean hasKick() {
    return kick_ != null;
  }
  /**
   * <pre>
   * The resulting kick.
   * </pre>
   *
   * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
   * @return The kick.
   */
  @java.lang.Override
  public network.cow.mooapis.session.v1.Kick getKick() {
    return kick_ == null ? network.cow.mooapis.session.v1.Kick.getDefaultInstance() : kick_;
  }
  /**
   * <pre>
   * The resulting kick.
   * </pre>
   *
   * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
   */
  @java.lang.Override
  public network.cow.mooapis.session.v1.KickOrBuilder getKickOrBuilder() {
    return getKick();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kick_ != null) {
      output.writeMessage(1, getKick());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kick_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getKick());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof network.cow.mooapis.session.v1.KickPlayerResponse)) {
      return super.equals(obj);
    }
    network.cow.mooapis.session.v1.KickPlayerResponse other = (network.cow.mooapis.session.v1.KickPlayerResponse) obj;

    if (hasKick() != other.hasKick()) return false;
    if (hasKick()) {
      if (!getKick()
          .equals(other.getKick())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasKick()) {
      hash = (37 * hash) + KICK_FIELD_NUMBER;
      hash = (53 * hash) + getKick().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static network.cow.mooapis.session.v1.KickPlayerResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static network.cow.mooapis.session.v1.KickPlayerResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(network.cow.mooapis.session.v1.KickPlayerResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cow.session.v1.KickPlayerResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cow.session.v1.KickPlayerResponse)
      network.cow.mooapis.session.v1.KickPlayerResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.cow.mooapis.session.v1.SessionServiceApi.internal_static_cow_session_v1_KickPlayerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.cow.mooapis.session.v1.SessionServiceApi.internal_static_cow_session_v1_KickPlayerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.cow.mooapis.session.v1.KickPlayerResponse.class, network.cow.mooapis.session.v1.KickPlayerResponse.Builder.class);
    }

    // Construct using network.cow.mooapis.session.v1.KickPlayerResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (kickBuilder_ == null) {
        kick_ = null;
      } else {
        kick_ = null;
        kickBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return network.cow.mooapis.session.v1.SessionServiceApi.internal_static_cow_session_v1_KickPlayerResponse_descriptor;
    }

    @java.lang.Override
    public network.cow.mooapis.session.v1.KickPlayerResponse getDefaultInstanceForType() {
      return network.cow.mooapis.session.v1.KickPlayerResponse.getDefaultInstance();
    }

    @java.lang.Override
    public network.cow.mooapis.session.v1.KickPlayerResponse build() {
      network.cow.mooapis.session.v1.KickPlayerResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public network.cow.mooapis.session.v1.KickPlayerResponse buildPartial() {
      network.cow.mooapis.session.v1.KickPlayerResponse result = new network.cow.mooapis.session.v1.KickPlayerResponse(this);
      if (kickBuilder_ == null) {
        result.kick_ = kick_;
      } else {
        result.kick_ = kickBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof network.cow.mooapis.session.v1.KickPlayerResponse) {
        return mergeFrom((network.cow.mooapis.session.v1.KickPlayerResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(network.cow.mooapis.session.v1.KickPlayerResponse other) {
      if (other == network.cow.mooapis.session.v1.KickPlayerResponse.getDefaultInstance()) return this;
      if (other.hasKick()) {
        mergeKick(other.getKick());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      network.cow.mooapis.session.v1.KickPlayerResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (network.cow.mooapis.session.v1.KickPlayerResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private network.cow.mooapis.session.v1.Kick kick_;
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.mooapis.session.v1.Kick, network.cow.mooapis.session.v1.Kick.Builder, network.cow.mooapis.session.v1.KickOrBuilder> kickBuilder_;
    /**
     * <pre>
     * The resulting kick.
     * </pre>
     *
     * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
     * @return Whether the kick field is set.
     */
    public boolean hasKick() {
      return kickBuilder_ != null || kick_ != null;
    }
    /**
     * <pre>
     * The resulting kick.
     * </pre>
     *
     * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
     * @return The kick.
     */
    public network.cow.mooapis.session.v1.Kick getKick() {
      if (kickBuilder_ == null) {
        return kick_ == null ? network.cow.mooapis.session.v1.Kick.getDefaultInstance() : kick_;
      } else {
        return kickBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The resulting kick.
     * </pre>
     *
     * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
     */
    public Builder setKick(network.cow.mooapis.session.v1.Kick value) {
      if (kickBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kick_ = value;
        onChanged();
      } else {
        kickBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The resulting kick.
     * </pre>
     *
     * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
     */
    public Builder setKick(
        network.cow.mooapis.session.v1.Kick.Builder builderForValue) {
      if (kickBuilder_ == null) {
        kick_ = builderForValue.build();
        onChanged();
      } else {
        kickBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The resulting kick.
     * </pre>
     *
     * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
     */
    public Builder mergeKick(network.cow.mooapis.session.v1.Kick value) {
      if (kickBuilder_ == null) {
        if (kick_ != null) {
          kick_ =
            network.cow.mooapis.session.v1.Kick.newBuilder(kick_).mergeFrom(value).buildPartial();
        } else {
          kick_ = value;
        }
        onChanged();
      } else {
        kickBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The resulting kick.
     * </pre>
     *
     * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
     */
    public Builder clearKick() {
      if (kickBuilder_ == null) {
        kick_ = null;
        onChanged();
      } else {
        kick_ = null;
        kickBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The resulting kick.
     * </pre>
     *
     * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
     */
    public network.cow.mooapis.session.v1.Kick.Builder getKickBuilder() {
      
      onChanged();
      return getKickFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The resulting kick.
     * </pre>
     *
     * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
     */
    public network.cow.mooapis.session.v1.KickOrBuilder getKickOrBuilder() {
      if (kickBuilder_ != null) {
        return kickBuilder_.getMessageOrBuilder();
      } else {
        return kick_ == null ?
            network.cow.mooapis.session.v1.Kick.getDefaultInstance() : kick_;
      }
    }
    /**
     * <pre>
     * The resulting kick.
     * </pre>
     *
     * <code>.cow.session.v1.Kick kick = 1 [json_name = "kick"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        network.cow.mooapis.session.v1.Kick, network.cow.mooapis.session.v1.Kick.Builder, network.cow.mooapis.session.v1.KickOrBuilder> 
        getKickFieldBuilder() {
      if (kickBuilder_ == null) {
        kickBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            network.cow.mooapis.session.v1.Kick, network.cow.mooapis.session.v1.Kick.Builder, network.cow.mooapis.session.v1.KickOrBuilder>(
                getKick(),
                getParentForChildren(),
                isClean());
        kick_ = null;
      }
      return kickBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cow.session.v1.KickPlayerResponse)
  }

  // @@protoc_insertion_point(class_scope:cow.session.v1.KickPlayerResponse)
  private static final network.cow.mooapis.session.v1.KickPlayerResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new network.cow.mooapis.session.v1.KickPlayerResponse();
  }

  public static network.cow.mooapis.session.v1.KickPlayerResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KickPlayerResponse>
      PARSER = new com.google.protobuf.AbstractParser<KickPlayerResponse>() {
    @java.lang.Override
    public KickPlayerResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KickPlayerResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KickPlayerResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KickPlayerResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public network.cow.mooapis.session.v1.KickPlayerResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

