// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/session/v1/types.proto

package network.cow.mooapis.session.v1;

public interface SessionIdentifierOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.session.v1.SessionIdentifier)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the session to receive.
   * </pre>
   *
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <pre>
   * The id of the session to receive.
   * </pre>
   *
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * The id of the session to receive.
   * </pre>
   *
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * The player to receive the session for.
   * </pre>
   *
   * <code>string player_id = 2 [json_name = "playerId"];</code>
   * @return Whether the playerId field is set.
   */
  boolean hasPlayerId();
  /**
   * <pre>
   * The player to receive the session for.
   * </pre>
   *
   * <code>string player_id = 2 [json_name = "playerId"];</code>
   * @return The playerId.
   */
  java.lang.String getPlayerId();
  /**
   * <pre>
   * The player to receive the session for.
   * </pre>
   *
   * <code>string player_id = 2 [json_name = "playerId"];</code>
   * @return The bytes for playerId.
   */
  com.google.protobuf.ByteString
      getPlayerIdBytes();

  public network.cow.mooapis.session.v1.SessionIdentifier.IdentifierCase getIdentifierCase();
}
