// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cow/session/v1/types.proto

package network.cow.mooapis.session.v1;

public interface StopCauseKickedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cow.session.v1.StopCauseKicked)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique identifier of the underlying kick.
   * </pre>
   *
   * <code>string kick_id = 1 [json_name = "kickId"];</code>
   * @return The kickId.
   */
  java.lang.String getKickId();
  /**
   * <pre>
   * The unique identifier of the underlying kick.
   * </pre>
   *
   * <code>string kick_id = 1 [json_name = "kickId"];</code>
   * @return The bytes for kickId.
   */
  com.google.protobuf.ByteString
      getKickIdBytes();

  /**
   * <pre>
   * The reason of the kick.
   * </pre>
   *
   * <code>string reason = 2 [json_name = "reason"];</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <pre>
   * The reason of the kick.
   * </pre>
   *
   * <code>string reason = 2 [json_name = "reason"];</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
